# trigger:
#   branches:
#     include:
#     - master

trigger: none
pr: none

stages:
- stage: build

  jobs:
    - job: Job
      pool:
        name: win-selfhosted

      steps:
      # - task: NodeTool@0
      #   inputs:
      #     versionSpec: '14.x'
      #   displayName: 'Install Node.js'
        
      - script: |
          npm install
        displayName: 'Install packages'    

      - script:           
          npm run build
        displayName: 'Run build'
      
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'dist/angular-devops'
          ArtifactName: 'ngapp'
          publishLocation: 'Container'
        displayName: 'Publish Artifacts'