# trigger:
#   branches:
#     include:
#     - master

trigger: none
pr: none

variables:
  buildfolder: az-static-webapp

stages:
- stage: build

  jobs:
    - job: Job
      pool:
        vmImage: 'ubuntu-latest'

      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '18.10.0'
        displayName: 'Install Node.js'

      - script: |
          npm install -g @angular/cli
          npm install
        displayName: 'install packages'

      - script:
          ng build
        displayName: 'npm build'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'dist/$(buildfolder)'
          ArtifactName: 'ngapp'
          publishLocation: 'Container'
        displayName: 'Publish Artifacts'
