name: angular ci

# trigger:
#   branches:
#     include:
#     - master

trigger: none
pr: none

variables:
  nodeVer: '18.10.0'
  dist: angular-devops

stages:
- stage: build

  jobs:
    - job: Job
      pool:
        vmImage: 'ubuntu-latest'

      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(nodeVer)
        displayName: Install Node $(nodeVer)

      - script: |
          npm install
        displayName: 'Install Packages'

      - script:
          npm run build
        displayName: 'Build'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'dist/$(dist)'
          ArtifactName: 'ngapp'
          publishLocation: 'Container'
        displayName: 'Publish Artifacts'
