name: cd static webapp

# trigger:
#   branches:
#     include:
#       - master

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest
  conAZ: scRG
  img: angular-devops:latest
  app: angular-demo-app
  rg: angular-11152

stages:
- stage: Deploy
  displayName: Deploy to ACA

  jobs:
    - job: Deploy
      steps:
      - task: AzureContainerApps@1
        inputs:
          azureSubscription: '$(conAZ)'
          imageToDeploy: '$(img)'
          containerAppName: '$(app)'
          resourceGroup: '$(rg)'
